// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:YOUR_APP_ID:web:YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'petwalk-350f4',
    authDomain: 'petwalk-350f4.firebaseapp.com',
    storageBucket: 'petwalk-350f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQOyYkBLZr11hc7sm_Km_UzuBwuQFX1gA',
    appId: '1:164810968514:android:a0ea3b4de4f26df70f9a5b',
    messagingSenderId: '164810968514',
    projectId: 'petwalk-350f4',
    storageBucket: 'petwalk-350f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9QRWMJ3O_qPiN6IKdFYzJoCjrR3-lkb4',
    appId: '1:164810968514:ios:e869f9cd2e69fabb0f9a5b',
    messagingSenderId: '164810968514',
    projectId: 'petwalk-350f4',
    storageBucket: 'petwalk-350f4.firebasestorage.app',
    iosBundleId: 'com.example.petwalkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9QRWMJ3O_qPiN6IKdFYzJoCjrR3-lkb4',
    appId: '1:164810968514:ios:e869f9cd2e69fabb0f9a5b',
    messagingSenderId: '164810968514',
    projectId: 'petwalk-350f4',
    storageBucket: 'petwalk-350f4.firebasestorage.app',
    iosBundleId: 'com.example.petwalkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzCva6AaMNR5FJHi5fJeAVtM1MTdQWD9g',
    appId: '1:164810968514:web:770ffcc2e4b7d8fd0f9a5b',
    messagingSenderId: '164810968514',
    projectId: 'petwalk-350f4',
    authDomain: 'petwalk-350f4.firebaseapp.com',
    storageBucket: 'petwalk-350f4.firebasestorage.app',
  );

}
